name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: devops
          POSTGRES_PASSWORD: devops
          POSTGRES_DB: devopsdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U devops"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r backend/requirements.txt

      - name: Rodar testes
        run: |
          pytest